### ISSUE TITLE
Wrap async

### ISSUE THREAD

**Issue by Slava** [peerlibrary/meteor-blocking#1]
Hi! Just FYI, there is work going on something similar, called Wrap async on separate branch in Meteor repo: https://github.com/meteor/meteor/tree/wrap-async .

It will be more sophisticated though, if you don't pass a callback - it becomes synchronous, otherwise it will be async. Support for optional arguments in the middle and stuff, @estark37 is working on it.

**Comment by mitar** [comment]
Glad to hear that. But doesn't really help me when I need to have things working _now_ and not next year. This is why I make such things and put them into packages. :-) I hope it will be as easy to use as it is this one. I am using it for doing [blocking AWS calls](https://github.com/peerlibrary/peerlibrary/blob/master/server/manage.coffee#L47). And it is really easy to do that with current function signature.

**Comment by mitar** [comment]
(So I hope it will not be more complicated with Wrap async.)

**Comment by estark37** [comment]
wrap-async is pretty much ready to merge into linker... I'm just waiting until I get back from vacation in case things blow up when I do the merge. We might be able to backport it into devel also. In any case, it should have pretty much the same signature as yours. Like Slava said, it'll make your function synchronous when you don't pass a callback and async when you do.

I like your idea of passing an optional this binding; I was thinking about doing that for wrapAsync and might still do it.

**Comment by mitar** [comment]
`this` is almost necessary when you have object methods you want to make synchronous. `AWS` does not work without that.

**Comment by mitar** [comment]
One other idea: you could also issue a warning/error if it is not inside the fiber, when called the function is eventually called?

**Comment by Slava** [comment]
or just make sure it is executed in binded environment? (inside fibers and stuff)

**Comment by estark37** [comment]
Yeah the current wrapAsync implementation wraps callbacks in bindEnvironment.

The alternative to a `this` argument is just `Foo.prototype.bar = function () { return wrapAsync(Foo.prototype._bar).apply(this, arguments); }`. We do that quite often though so it's probably worth having the this argument to wrapAsync.

**Comment by mitar** [comment]
This was one thing I was thinking about for my function. Automatic wrapping into `Meteor.bindEnvironment`. But then decided against that because sometimes you want to call `Meteor.bindEnvironment` somewhere else (where you are still in correct Meteor fiber) and you want it to blow up otherwise, to teach you that.

**Comment by mitar** [comment]
Or yes, you could `Meteor.bindEnvironment` at the time of creation, and not at time of calling the callback. Hmm.

**Comment by Slava** [comment]
I am not sure how does bindEnvironment treat callback if it is already in some fiber. Will it create new fiber in any case or just in case it's needed?

**Comment by mitar** [comment]
What do you pass for error handling function?

> Will it create new fiber in any case or just in case it's needed?

It does it only if needed.

**Comment by mitar** [comment]
> We do that quite often though so it's probably worth having the this argument to wrapAsync.

Oh, no. Setting prototype is cleaner. I forget about that. I think we should then just document this, so that users know how to do it for objects, but then there is no need to take `this`. If somebody still wants to use `this`, you can use `bind` probably.

**Comment by mitar** [comment]
OK, I found that passing `this` to function can be easier when you are not constructing your own object, but using an existing one. Like what I am using in my [AWS readme](https://github.com/peerlibrary/meteor-aws-sdk).

**Comment by mitar** [comment]
@imslavko: Where did the wrap-async tree go?

**Comment by Slava** [comment]
Hey there,

the branch was merged to devel long time ago. It is available as `Meteor._wrapAsync` on devel and 0.6.5-rc14

**Comment by mizzao** [comment]
I just saw this package on Atmosphere and was about to ask "Why did you make this?" - then I saw this thread.

**Comment by mitar** [comment]
Yes, it is mostly just a compatibility package now. With a slightly different API. But I even internally migrated to use `Meteor._wrapAsync`, so it is just a wrapper for `Meteor._wrapAsync` now.

**Comment by mitar** [comment]
In fact there is a small but important difference. [Meteor.wrapAsync](http://docs.meteor.com/#/full/meteor_wrapasync) cannot accept a function as the last argument. It switches to the callback mode. But this package does not behave like that. So you can use `Meteor.wrapAsync` if you want that callback behavior. Or `blocking` if you want to wrap a function no matter what.
