### ISSUE TITLE
Meteor 0.9.0 update?

### ISSUE THREAD

**Issue by tejasmanohar** [peerlibrary/meteor-blocking#2]
Hey, is it safe to install with meteor 0.9.0 update? If so, what command using the `meteor` and not `mrt` new package system?

**Comment by mitar** [comment]
Sorry. I have not moved to 0.9.0 myself, so I don't know the answer to this question.

**Comment by tejasmanohar** [comment]
Ok. Keep me posted if you ever get a chance.

**Comment by mitar** [comment]
Done.
